name: grafana
summary: Grafana is a general purpose dashboard and graph composer.
maintainers: 
        - Ian Booth <ian.booth@canonical.com>
        - Michael Hudson-Doyle <michael.hudson@canonical.com>
        - Matthew Williams <matthew.williams@canonical.com>
        - Cheryl Jennings <cheryl.jennings@canonical.com>
        - Eric Snow <eric.snow@canonical.com>
description: |
  This will install and setup grafana behind nginx.
  It supports getting data from influx db via the query relation
  to the influxdb charm.
tags:
  - monitoring
requires:
  query:
    interface: influxdb-http
